from app.windows.tool_window import ToolWindow
from app.windows.create_new_project_window import CreateNewProjectWindow
from app.windows.splashscreen_window import SplashscreenWindow
from app.windows.mouse_pos_window import MousePositionWindow